name: Test API with EF Core + SQLite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore DatingApp.sln


    - name: Build
      run: dotnet build API --no-restore --configuration Release

    - name: Apply EF Core migrations
      run: |
        cd API
        dotnet tool install --global dotnet-ef
        export PATH="$PATH:$HOME/.dotnet/tools"
        dotnet ef database update
        cd ..

    - name: Run API in background
      run: |
        dotnet run --project API --urls "http://localhost:5001" &
        sleep 5

    - name: Insert a user into SQLite
      run: |
        sudo apt-get install -y sqlite3
        sqlite3 API/dating.db "INSERT INTO Users (Id, DisplayName, Email) VALUES ('gh-test', 'GitHub Bot', 'bot@test.com');"

    - name: Call /api/members
      run: |
        curl -v http://localhost:5001/api/members
